name: Run E2E tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with: 
          node_version: 20

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          NEXT_PUBLIC_API_BASE_URL: "https://devstore-api-beta.vercel.app"
          APP_URL: "http://localhost:3000"
        with:
          build: npm run build
          start: npm start